#ifndef FADESTYLE_H
#define FADESTYLE_H

enum FadeStyle {
	FadeRandom,
	FadeStatic,
	FadeMoveRight,
	FadeMoveLeft,
	FadeMoveDown,
	FadeMoveUp,
	FadeOverlayRight,
	FadeOverlayLeft,
	FadeOverlayDown,
	FadeOverlayUp,
	FadeOpenHorizontal,
	FadeOpenVertical,
	FadeCloseHorizontal,
	FadeCloseVertical,
	FadeOutHorizontal,
	FadeOutVertical,
	FadeShutterDown,
	FadeShutterUp,
	FadeBlink,
	FadeOutRight,
	FadeOutLeft,
	FadeOutDown,
	FadeOutUp,
	FadePageLeft,
	FadePageRight,
	FadeOpenFan,
	FadeCloseFan,
	FadeSpinLeft,
	FadeSpinRight,
	FadePullDown,
	FadePullUp,
	FadeRollDown,
	FadeRollRight,
	FadeGrid,
	FadeContrastBlink,
	FadeExpandRectangle,
	FadeShrinkRectangle,
	FadePullRight,
	FadePullLeft,
	FadeExpandCross,
	FadeShrinkCross,
	FadeRectangleTopLeft,
	FadeRectangleTopRight,
	FadeRectangleBottomLeft,
	FadeRectangleBottomRight,
	FadeDiagonalTopLeft,
	FadeDiagonalTopRight,
	FadeDiagonalBottomLeft,
	FadeDiagonalBottomRight,
	FadeSolidDown,
	FadeSolidUp,
	FadeMoveLeftContinuous,
	FadeMoveUpContinuous,
	FadeMoveRightContinuous,
	FadeMoveDownContinuous,
	FadeMax
};

#endif // FADESTYLE_H
